#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrdb -load ~/.config/xorg/xresources

setxkbmap -option terminate:ctrl_alt_bksp
setxkbmap -option caps:swapescape
setxkbmap -option ctrl:swap_lalt_lctl

dunst &
canto-daemon &
transmission-daemon &

exec i3
