" execute pathogen#infect()

set backspace=indent,eol,start
syntax on
filetype plugin indent on
set number
set hidden
set nocompatible
set showtabline=2
set noshowmode
set t_Co=256
set laststatus=2

set viminfo=""

" let g:powerline_pycmd='py3'
" set rtp+=$HOME/.local/lib/python3.5/site-packages/powerline/bindings/vim/
"
" set shell=bash\ -i
" let g:gruvbox_italic=1
" let g:gruvbox_contrast_dark='hard'
" colorscheme gruvbox
" set background=dark
"
" map <C-n> :NERDTreeToggle<CR>
