POWERLEVL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs background_jobs status)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

POWERLEVEL9K_DIR_HOME_FOREGROUND='236'
POWERLEVEL9K_DIR_HOME_BACKGROUND='253'

POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='236'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='253'

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='236'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='253'

## STATUS
POWERLEVEL9K_OK_ICON=''
POWERLEVEL9K_CARRIAGE_RETURN_ICON=' '

POWERLEVEL9K_STATUS_OK_BACKGROUND='028'
POWERLEVEL9K_STATUS_OK_FOREGROUND='253'

POWERLEVEL9K_STATUS_ERROR_BACKGROUND='088'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='253'

## VCS
POWERLEVEL9K_SHOW_CHANGESET='true'
POWERLEVEL9K_CHANGESET_HASH_LENGTH='6'

POWERLEVEL9K_VCS_FOREGROUND='250'
POWERLEVEL9K_VCS_BACKGROUND='240'

POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='232'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='240'

POWERLEVEL9K_VCS_ACTIONFORMAT_FOREGROUND='088'
POWERLEVEL9K_VCS_ACTIONFORMAT_BACKGROUND='063'

POWERLEVEL9K_VCS_BRANCH_ICON='   '
POWERLEVEL9K_VCS_GIT_ICON=' ' 
POWERLEVEL9K_VCS_COMMIT_ICON=' '
POWERLEVEL9K_VCS_UNTRACKED_ICON=' '
POWERLEVEL9K_VCS_BOOKMARK_ICON='  '
POWERLEVEL9K_VCS_HG_ICON='  ' 
POWERLEVEL9K_VCS_STASH_ICON='  '
POWERLEVEL9K_VCS_STAGED_ICON='  '
POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON='  '
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='  '
POWERLEVEL9K_VCS_TAG_ICON='  ' 
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='  '
POWERLEVEL9K_VCS_UNSTAGED_ICON='  '
